AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation for testing Hybris with redis.'
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
  AMIID:
    Type:  AWS::EC2::Image::Id
    Default: 'ami-042e8287309f5df03'
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
Resources:
  HybrisEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 'm5.2xlarge'
      SecurityGroupIds: !Ref SecurityGroups
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'AMIID'
      SubnetId: !Ref 'SubnetId'
      Tags:
        - Key: 'Name'
          Value: 'Test-Hybris-Server'
        - Key: 'Environment'
          Value: 'Test'
        - Key: 'Application'
          Value: 'Hybris'
        - Key: 'CostCenter'
          Value: 'IT-HY-01'
        - Key: 'PowerOff'
          Value: 'Yes'
Outputs:
  InstanceId:
    Description: InstanceId of the newly hybris created EC2 instance
    Value: !Ref 'HybrisEC2Instance'
  PrivateIP:
    Description: Private IP address of the newly created EC2 instance
    Value: !GetAtt [HybrisEC2Instance, PrivateIp]
